"""OpenTelemetry、Langfuse 和 agentos 观测字段常量。"""

LANGFUSE_OBSERVATION_TYPE = "langfuse.observation.type"
LANGFUSE_OBSERVATION_INPUT = "langfuse.observation.input"
LANGFUSE_OBSERVATION_OUTPUT = "langfuse.observation.output"
LANGFUSE_OBSERVATION_MODEL_NAME = "langfuse.observation.model.name"
LANGFUSE_OBSERVATION_USAGE_DETAILS = "langfuse.observation.usage_details"
LANGFUSE_TRACE_NAME = "langfuse.trace.name"
LANGFUSE_TRACE_INPUT = "langfuse.trace.input"
LANGFUSE_TRACE_OUTPUT = "langfuse.trace.output"
LANGFUSE_SESSION_ID = "langfuse.session.id"
LANGFUSE_USER_ID = "langfuse.user.id"
LANGFUSE_TRACE_METADATA_CAPTURE_MODE = "langfuse.trace.metadata.capture_mode"
LANGFUSE_TRACE_METADATA_TURN_ID = "langfuse.trace.metadata.turn_id"

USER_ID = "user.id"
SESSION_ID = "session.id"

GEN_AI_OPERATION_NAME = "gen_ai.operation.name"
GEN_AI_PROVIDER_NAME = "gen_ai.provider.name"
GEN_AI_REQUEST_MODEL = "gen_ai.request.model"
GEN_AI_RESPONSE_MODEL = "gen_ai.response.model"
GEN_AI_RESPONSE_ID = "gen_ai.response.id"
GEN_AI_RESPONSE_FINISH_REASONS = "gen_ai.response.finish_reasons"
GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens"
GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens"
GEN_AI_USAGE_TOTAL_TOKENS = "gen_ai.usage.total_tokens"
GEN_AI_TOOL_NAME = "gen_ai.tool.name"
GEN_AI_TOOL_CALL_ID = "gen_ai.tool.call.id"

AGENTOS_SESSION_ID = "agentos.session.id"
AGENTOS_TURN_ID = "agentos.turn.id"
AGENTOS_TRACE_ID = "agentos.trace.id"
AGENTOS_USER_ID = "agentos.user.id"
AGENTOS_CAPTURE_MODE = "agentos.capture.mode"
