"""运行时请求构建、typed events 与 loop 调度。"""

from agentos._waiting import AgentWaiting, WaitReason
from agentos.events import (
    AgentContinuationFailedEvent,
    AgentInboxBackpressureEvent,
    AgentTaskCancelledEvent,
    AgentTaskCompletedEvent,
    AgentTaskDispatchedEvent,
    AgentTaskFailedEvent,
    AgentTaskLateResultReceivedEvent,
    AssistantMessageAppendedEvent,
    ChapterStartedEvent,
    CompressedSegmentAppendedEvent,
    CompressionCompletedEvent,
    CompressionFailedEvent,
    CompressionSkippedEvent,
    ContextRenderedEvent,
    EventBus,
    InheritedStateSetEvent,
    MemoryContextSetEvent,
    ProviderRequestBuiltEvent,
    ProviderResponseReceivedEvent,
    ProviderRetryEvent,
    AgentEvent,
    RecallContextFailedEvent,
    RecallContextInjectedEvent,
    RecallContextRequestedEvent,
    SnapshotLoadedEvent,
    SnapshotSavedEvent,
    SubagentSpawnedEvent,
    ToolCallRequestedEvent,
    ToolExecutionCompletedEvent,
    ToolExecutionStartedEvent,
    ToolResultAppendedEvent,
    ToolResultCappedEvent,
    TurnCompletedEvent,
    TurnFailedEvent,
    TurnStartedEvent,
    UserMessageAppendedEvent,
    WorkingStateSchemaDeclaredEvent,
    WorkingStateSchemaExtendedEvent,
    WorkingStateUpdatedEvent,
)
from agentos.runtime.agent import Agent
from agentos.runtime.agent_stream import AgentStream
from agentos.runtime.durable_commands import DurableCommandReceipt, DurableRunCommand
from agentos.runtime.errors import (
    AgentBusyError,
    AgentRunError,
    AgentStreamClosedError,
    AgentStreamConsumerError,
    ContinuationUnavailableError,
    RunProtocolError,
    WaitingUnsupportedError,
)
from agentos.runtime.profile import (
    LocalRuntimeProfile,
    RuntimeProfile,
)
from agentos.runtime.provider_request_builder import ProviderRequestBuilder
from agentos.runtime.query_loop import QueryLoop, TurnNoticeProvider
from agentos.runtime.retry import ProviderCircuitOpenError, RetryPolicy
from agentos.runtime.run import (
    AgentResult,
    LocalContinuationInput,
    RunInput,
    RunOptions,
    RunOutcome,
    RunRequest,
    UserTurnInput,
)
from agentos.runtime.session import SessionState
from agentos.runtime.side_effect_resolution import (
    side_effect_resolution_from_payload,
    side_effect_resolution_to_payload,
)
from agentos.runtime.side_effect_resume import SideEffectResume
from agentos.runtime.side_effect_types import (
    SideEffectResolution,
    SideEffectResolutionKind,
)
from agentos.runtime.stream_events import (
    AssistantCompleted,
    AssistantContentDelta,
    AssistantThinkingDelta,
    ContextLoaded,
    FinalResult,
    PlanUpdated,
    SkillLoaded,
    StatusUpdate,
    ToolStreamCompleted,
    ToolStreamFailed,
    ToolStreamStarted,
    TurnStreamCancelled,
    TurnStreamCompleted,
    TurnStreamEvent,
    TurnStreamFailed,
    TurnStreamStarted,
    TurnStreamWaiting,
)
from agentos.runtime.stream_serializers import (
    event_payload,
    event_to_json,
    event_to_sse,
    event_type,
    iter_jsonl,
    iter_sse,
)
from agentos.runtime.turn import TurnState

__all__ = [
    "Agent",
    "AgentBusyError",
    "AgentContinuationFailedEvent",
    "AgentInboxBackpressureEvent",
    "AgentTaskCancelledEvent",
    "AgentTaskCompletedEvent",
    "AgentTaskDispatchedEvent",
    "AgentTaskFailedEvent",
    "AgentTaskLateResultReceivedEvent",
    "AssistantCompleted",
    "AssistantContentDelta",
    "AssistantMessageAppendedEvent",
    "AssistantThinkingDelta",
    "AgentResult",
    "AgentRunError",
    "AgentStream",
    "AgentStreamClosedError",
    "AgentStreamConsumerError",
    "AgentWaiting",
    "ChapterStartedEvent",
    "CompressedSegmentAppendedEvent",
    "CompressionCompletedEvent",
    "CompressionFailedEvent",
    "CompressionSkippedEvent",
    "ContextRenderedEvent",
    "ContextLoaded",
    "ContinuationUnavailableError",
    "DurableCommandReceipt",
    "DurableRunCommand",
    "EventBus",
    "InheritedStateSetEvent",
    "LocalRuntimeProfile",
    "LocalContinuationInput",
    "MemoryContextSetEvent",
    "ProviderRequestBuilder",
    "ProviderRequestBuiltEvent",
    "ProviderResponseReceivedEvent",
    "ProviderRetryEvent",
    "ProviderCircuitOpenError",
    "QueryLoop",
    "RetryPolicy",
    "RunOptions",
    "RunInput",
    "RunOutcome",
    "RunProtocolError",
    "RunRequest",
    "RuntimeProfile",
    "AgentEvent",
    "RecallContextFailedEvent",
    "RecallContextInjectedEvent",
    "RecallContextRequestedEvent",
    "SessionState",
    "SideEffectResolution",
    "SideEffectResolutionKind",
    "SideEffectResume",
    "SkillLoaded",
    "SnapshotLoadedEvent",
    "SnapshotSavedEvent",
    "SubagentSpawnedEvent",
    "StatusUpdate",
    "ToolCallRequestedEvent",
    "ToolExecutionCompletedEvent",
    "ToolExecutionStartedEvent",
    "ToolResultAppendedEvent",
    "ToolResultCappedEvent",
    "ToolStreamCompleted",
    "ToolStreamFailed",
    "ToolStreamStarted",
    "PlanUpdated",
    "FinalResult",
    "TurnCompletedEvent",
    "TurnFailedEvent",
    "TurnStreamCancelled",
    "TurnStreamCompleted",
    "TurnStreamEvent",
    "TurnStreamFailed",
    "TurnStreamStarted",
    "TurnStreamWaiting",
    "TurnStartedEvent",
    "TurnState",
    "TurnNoticeProvider",
    "UserMessageAppendedEvent",
    "UserTurnInput",
    "WaitingUnsupportedError",
    "WaitReason",
    "WorkingStateSchemaDeclaredEvent",
    "WorkingStateSchemaExtendedEvent",
    "WorkingStateUpdatedEvent",
    "event_payload",
    "event_to_json",
    "event_to_sse",
    "event_type",
    "iter_jsonl",
    "iter_sse",
    "side_effect_resolution_from_payload",
    "side_effect_resolution_to_payload",
]
